// flow-typed signature: 6e3d02e84251debe43dd5ab7ed887875
// flow-typed version: <<STUB>>/detectie_v^1.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'detectie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'detectie' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'detectie/detectie' {
  declare module.exports: any
}

declare module 'detectie/test/test' {
  declare module.exports: any
}

// Filename aliases
declare module 'detectie/detectie.js' {
  declare module.exports: $Exports<'detectie/detectie'>
}
declare module 'detectie/test/test.js' {
  declare module.exports: $Exports<'detectie/test/test'>
}
