// flow-typed signature: 8f3e187dcc0b2e6544d0dcdf43ca0b73
// flow-typed version: <<STUB>>/geolib_v^2.0.22/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'geolib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'geolib' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'geolib/dist/geolib.elevation' {
  declare module.exports: any
}

declare module 'geolib/dist/geolib' {
  declare module.exports: any
}

// Filename aliases
declare module 'geolib/dist/geolib.elevation.js' {
  declare module.exports: $Exports<'geolib/dist/geolib.elevation'>
}
declare module 'geolib/dist/geolib.js' {
  declare module.exports: $Exports<'geolib/dist/geolib'>
}
